// USD to ZAR exchange rate (approximate)
export const USD_TO_ZAR = 18.5;

export const courses = [
    {
    id: 1,
    title: "Smart Contracts & DeFi Development",
    description: "Build and deploy smart contracts on Ethereum and Solana. Master Solidity, Web3.js, DeFi protocols, yield farming mechanics, and decentralized exchange architecture.",
    priceUSD: 180.00,
    category: "Blockchain",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/1e0f09ffc_generated_0326c7fa.png",
    duration: "12 weeks",
    students: 1320,
    rating: 4.7,
    featured: false,
  },
  {
    id: 2,
    title: "Network Security & Firewall Management",
    description: "Master network security protocols, firewall configuration, intrusion detection systems, VPN setup, and network monitoring tools used by enterprise security teams worldwide.",
    priceUSD: 350.00,
    category: "Cybersecurity",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/69803f2a8_generated_446c7086.png",
    duration: "16 weeks",
    students: 2100,
    rating: 4.6,
    featured: false,
  },
  {
    id: 3,
    title: "Crypto Trading & Blockchain Investment",
    description: "Learn advanced cryptocurrency trading strategies, technical analysis, portfolio management, risk assessment, and the fundamentals of blockchain-based financial instruments.",
    priceUSD: 600.00,
    category: "Blockchain",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/60cfaa183_generated_9eefcf29.png",
    duration: "16 weeks",
    students: 3450,
    rating: 4.8,
    featured: false,
  },
  {
    id: 4,
    title: "Advanced Web Development Mastery Course",
    description: "A 20-week advanced web-development program covering TypeScript, GraphQL, microservices, Docker, CI/CD, cloud deployment, automated testing, monitoring, and large-scale architecture.",
    priceUSD: 950.00,
    category: "Web Development",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/2f4999616_generated_eb437a0e.png",
    duration: "20 weeks",
    students: 2450,
    rating: 4.9,
    featured: true,
  },
  {
    id: 5,
    title: "Cloud Security & Infrastructure Protection",
    description: "Comprehensive course on securing cloud environments including AWS, Azure, and GCP. Learn identity management, encryption, compliance frameworks, and zero-trust architecture.",
    priceUSD: 1300.00,
    category: "Cybersecurity",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/befd07007_generated_bfb5f50d.png",
    duration: "20 weeks",
    students: 1540,
    rating: 4.8,
    featured: false,
  },
  {
    id: 6,
    title: "Cybersecurity Fundamentals & Threat Defense",
    description: "Master the core principles of cybersecurity including threat analysis, vulnerability assessment, incident response, and building robust defense strategies for modern enterprises.",
    priceUSD: 1500.00,
    category: "Cybersecurity",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/ec45a2222_generated_29b40169.png",
    duration: "20 weeks",
    students: 3120,
    rating: 4.8,
    featured: false,
  },
  {
    id: 7,
    title: "Blockchain Development & Architecture",
    description: "Deep dive into blockchain fundamentals, consensus mechanisms, distributed ledger technology, and building decentralized applications from scratch using modern frameworks.",
    priceUSD: 1780.00,
    category: "Blockchain",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/0e32cfe37_generated_7618056c.png",
    duration: "24 weeks",
    students: 1870,
    rating: 4.7,
    featured: false,
  },
  {
    id: 8,
    title: "Ethical Hacking & Penetration Testing",
    description: "Learn professional penetration testing methodologies, exploit development, social engineering techniques, and how to conduct comprehensive security audits for organizations.",
    priceUSD: 1850.00,
    category: "Cybersecurity",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/9c5ed6ab7_generated_31b41b51.png",
    duration: "36 weeks",
    students: 2780,
    rating: 4.9,
    featured: false,
  },


];

export const instructors = [
  {
    name: "Dr. Adrian Cole",
    title: "Lead Cybersecurity Instructor",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/87500c784_generated_image.png",
    experience: "18 Years",
    credentials: ["CISSP", "CEH", "OSCP"],
    bio: "Former Head of Security Operations at a FTSE 100 financial institution. Adrian has led incident response teams across 12 countries and holds a PhD in Information Security from Imperial College London.",
    highlights: [
      "Led security for 3 major bank mergers",
      "Published researcher — 40+ peer-reviewed papers",
      "Keynote speaker at Black Hat & DEF CON",
      "Ex-GCHQ cybersecurity consultant",
    ],
    courses: ["Cybersecurity Fundamentals & Threat Defense", "Ethical Hacking & Penetration Testing", "Network Security & Firewall Management"],
  },
  {
    name: "Priya Naidoo",
    title: "Blockchain & DeFi Lead",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/2023d7442_generated_image.png",
    experience: "14 Years",
    credentials: ["CFA", "CBP", "Ethereum Dev Cert"],
    bio: "Co-founder of a blockchain infrastructure company acquired by a top-5 crypto exchange. Priya previously served as Chief Blockchain Architect at a global consulting firm and advises several DeFi protocols.",
    highlights: [
      "Co-founded a blockchain startup (acquired 2021)",
      "Architected $2B+ in on-chain transaction infrastructure",
      "Advisor to 6 live DeFi protocols",
      "Regular contributor to the Ethereum Foundation",
    ],
    courses: ["Blockchain Development & Architecture", "Smart Contracts & DeFi Development", "Crypto Trading & Blockchain Investment"],
  },
  {
    name: "Marcus Steyn",
    title: "Senior Web & Cloud Security Instructor",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/519655160_generated_image.png",
    experience: "16 Years",
    credentials: ["AWS SAA", "GCP Pro", "CCSP"],
    bio: "Former Principal Engineer at two Fortune 500 tech companies, Marcus has architected cloud-native systems serving hundreds of millions of users. He specialises in scalable, secure web infrastructure and zero-trust architecture.",
    highlights: [
      "Architected cloud infra for 200M+ active users",
      "Ex-Principal Engineer at two Fortune 500 firms",
      "AWS & GCP certified trainer",
      "Open-source contributor — 12K+ GitHub stars",
    ],
    courses: ["Advanced Web Development Mastery Course", "Cloud Security & Infrastructure Protection"],
  },
];

export const testimonials = [
  {
    name: "Marcus Williams",
    role: "Security Analyst",
    text: "The cybersecurity course completely transformed my understanding of network security. The practical exercises were invaluable.",
    avatar: "MW",
  },
  {
    name: "Elena Rodriguez",
    role: "Blockchain Developer",
    text: "Outstanding blockchain investment strategies course. I've successfully applied the techniques and seen great results in my portfolio.",
    avatar: "ER",
  },
  {
    name: "James Thompson",
    role: "IT Manager",
    text: "Excellent content and presentation. The instructors are clearly experts in their field and explain complex concepts very well.",
    avatar: "JT",
  },
];